'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class en_US
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Presentacion.en-US", GetType(en_US).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error.
        '''</summary>
        Friend Shared ReadOnly Property _error() As String
            Get
                Return ResourceManager.GetString("error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Access Denied.
        '''</summary>
        Friend Shared ReadOnly Property acceso_denegado() As String
            Get
                Return ResourceManager.GetString("acceso_denegado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Accept.
        '''</summary>
        Friend Shared ReadOnly Property aceptar() As String
            Get
                Return ResourceManager.GetString("aceptar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Family Antecedents.
        '''</summary>
        Friend Shared ReadOnly Property antecedentes_familiares() As String
            Get
                Return ResourceManager.GetString("antecedentes_familiares", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Working Antecedents.
        '''</summary>
        Friend Shared ReadOnly Property antecedentes_laborales() As String
            Get
                Return ResourceManager.GetString("antecedentes_laborales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Last Name.
        '''</summary>
        Friend Shared ReadOnly Property apellidos() As String
            Get
                Return ResourceManager.GetString("apellidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Authentication.
        '''</summary>
        Friend Shared ReadOnly Property autenticacion() As String
            Get
                Return ResourceManager.GetString("autenticacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Search.
        '''</summary>
        Friend Shared ReadOnly Property busqueda() As String
            Get
                Return ResourceManager.GetString("busqueda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Head.
        '''</summary>
        Friend Shared ReadOnly Property cabeza() As String
            Get
                Return ResourceManager.GetString("cabeza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Street.
        '''</summary>
        Friend Shared ReadOnly Property calle() As String
            Get
                Return ResourceManager.GetString("calle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property cancelar() As String
            Get
                Return ResourceManager.GetString("cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Close Session.
        '''</summary>
        Friend Shared ReadOnly Property cerrar_sesion() As String
            Get
                Return ResourceManager.GetString("cerrar_sesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ID.
        '''</summary>
        Friend Shared ReadOnly Property ci() As String
            Get
                Return ResourceManager.GetString("ci", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirmation.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion() As String
            Get
                Return ResourceManager.GetString("confirmacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to change your password?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_cambiar_contrasenna() As String
            Get
                Return ResourceManager.GetString("confirmacion_cambiar_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to close your session?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_cerrar_sesion() As String
            Get
                Return ResourceManager.GetString("confirmacion_cerrar_sesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to delete the selected desease?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_enfermedades_eliminar() As String
            Get
                Return ResourceManager.GetString("confirmacion_enfermedades_eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to end the chat?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_finalizar_chat() As String
            Get
                Return ResourceManager.GetString("confirmacion_finalizar_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Do you want to have a chat with a doctor in order to get a more precise diagnosis?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_iniciar_chat() As String
            Get
                Return ResourceManager.GetString("confirmacion_iniciar_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to delete the selected patients?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_paciente_eliminar() As String
            Get
                Return ResourceManager.GetString("confirmacion_paciente_eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to delete the selected symptom?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_sintoma_eliminar() As String
            Get
                Return ResourceManager.GetString("confirmacion_sintoma_eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to  delete the [COUNT] selected symptoms?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_sintoma_eliminar_varios() As String
            Get
                Return ResourceManager.GetString("confirmacion_sintoma_eliminar_varios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirm new password.
        '''</summary>
        Friend Shared ReadOnly Property confirmar_nueva_contrasenna() As String
            Get
                Return ResourceManager.GetString("confirmar_nueva_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Appointment ended.
        '''</summary>
        Friend Shared ReadOnly Property consulta_finalizada() As String
            Get
                Return ResourceManager.GetString("consulta_finalizada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password.
        '''</summary>
        Friend Shared ReadOnly Property contrasenna() As String
            Get
                Return ResourceManager.GetString("contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Autogenerated password detected.
        '''</summary>
        Friend Shared ReadOnly Property contrasenna_autogenerada_detectada() As String
            Get
                Return ResourceManager.GetString("contrasenna_autogenerada_detectada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password changed succesfully.
        '''</summary>
        Friend Shared ReadOnly Property contrasenna_cambiada_exito() As String
            Get
                Return ResourceManager.GetString("contrasenna_cambiada_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chronic.
        '''</summary>
        Friend Shared ReadOnly Property cronica() As String
            Get
                Return ResourceManager.GetString("cronica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Any.
        '''</summary>
        Friend Shared ReadOnly Property cualquiera() As String
            Get
                Return ResourceManager.GetString("cualquiera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Department.
        '''</summary>
        Friend Shared ReadOnly Property departamento() As String
            Get
                Return ResourceManager.GetString("departamento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description.
        '''</summary>
        Friend Shared ReadOnly Property descripcion() As String
            Get
                Return ResourceManager.GetString("descripcion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Details.
        '''</summary>
        Friend Shared ReadOnly Property detalles() As String
            Get
                Return ResourceManager.GetString("detalles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a S.
        '''</summary>
        Friend Shared ReadOnly Property dia_domingo() As String
            Get
                Return ResourceManager.GetString("dia_domingo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Th.
        '''</summary>
        Friend Shared ReadOnly Property dia_jueves() As String
            Get
                Return ResourceManager.GetString("dia_jueves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a M.
        '''</summary>
        Friend Shared ReadOnly Property dia_lunes() As String
            Get
                Return ResourceManager.GetString("dia_lunes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tu.
        '''</summary>
        Friend Shared ReadOnly Property dia_martes() As String
            Get
                Return ResourceManager.GetString("dia_martes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a W.
        '''</summary>
        Friend Shared ReadOnly Property dia_miercoles() As String
            Get
                Return ResourceManager.GetString("dia_miercoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sat.
        '''</summary>
        Friend Shared ReadOnly Property dia_sabado() As String
            Get
                Return ResourceManager.GetString("dia_sabado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Days.
        '''</summary>
        Friend Shared ReadOnly Property dias() As String
            Get
                Return ResourceManager.GetString("dias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Address.
        '''</summary>
        Friend Shared ReadOnly Property direccion() As String
            Get
                Return ResourceManager.GetString("direccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Number.
        '''</summary>
        Friend Shared ReadOnly Property direccion_numero() As String
            Get
                Return ResourceManager.GetString("direccion_numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Age.
        '''</summary>
        Friend Shared ReadOnly Property edad() As String
            Get
                Return ResourceManager.GetString("edad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete.
        '''</summary>
        Friend Shared ReadOnly Property eliminar() As String
            Get
                Return ResourceManager.GetString("eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email.
        '''</summary>
        Friend Shared ReadOnly Property email() As String
            Get
                Return ResourceManager.GetString("email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Employee.
        '''</summary>
        Friend Shared ReadOnly Property empleado() As String
            Get
                Return ResourceManager.GetString("empleado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a [TIPO_EMPLEADO] successfully added..
        '''</summary>
        Friend Shared ReadOnly Property empleado_ingresado_exito() As String
            Get
                Return ResourceManager.GetString("empleado_ingresado_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Employees.
        '''</summary>
        Friend Shared ReadOnly Property empleados() As String
            Get
                Return ResourceManager.GetString("empleados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desease.
        '''</summary>
        Friend Shared ReadOnly Property enfermedad() As String
            Get
                Return ResourceManager.GetString("enfermedad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desease successfully imported..
        '''</summary>
        Friend Shared ReadOnly Property enfermedad_import_exito() As String
            Get
                Return ResourceManager.GetString("enfermedad_import_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desease successfully added..
        '''</summary>
        Friend Shared ReadOnly Property enfermedad_ingresada_exito() As String
            Get
                Return ResourceManager.GetString("enfermedad_ingresada_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desease successfully modified..
        '''</summary>
        Friend Shared ReadOnly Property enfermedad_modificada_exito() As String
            Get
                Return ResourceManager.GetString("enfermedad_modificada_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Disease.
        '''</summary>
        Friend Shared ReadOnly Property enfermedades() As String
            Get
                Return ResourceManager.GetString("enfermedades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please enter at least one last name..
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_apellidos() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_apellidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Field &apos;Street&apos; is mandatory..
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_calle() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_calle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Field &apos;ID&apos; is mandatory.
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_ci() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_ci", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Field &apos;Disease&apos; is mandatory..
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_enfermedad_nombre() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_enfermedad_nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Field &apos;Town&apos; is mandatory..
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_localidad() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_localidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Field &apos;Name&apos; is mandatory.
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_nombre() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Field &apos;Symptom&apos; is mandatory..
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_nombre_sintoma() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_nombre_sintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Field &apos;Number&apos; is mandatory..
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_numero() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Invalid ID..
        '''</summary>
        Friend Shared ReadOnly Property error_ci_invalida() As String
            Get
                Return ResourceManager.GetString("error_ci_invalida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Incorrect ID or password.
        '''</summary>
        Friend Shared ReadOnly Property error_credenciales_incorrectas() As String
            Get
                Return ResourceManager.GetString("error_credenciales_incorrectas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description too long..
        '''</summary>
        Friend Shared ReadOnly Property error_descripcion_larga() As String
            Get
                Return ResourceManager.GetString("error_descripcion_larga", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to delete the employee..
        '''</summary>
        Friend Shared ReadOnly Property error_eliminar_empleado() As String
            Get
                Return ResourceManager.GetString("error_eliminar_empleado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to delete desease [NOMBRE_ENFERMEDAD] .
        '''</summary>
        Friend Shared ReadOnly Property error_enfermedad_eliminar() As String
            Get
                Return ResourceManager.GetString("error_enfermedad_eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to add desease.
        '''</summary>
        Friend Shared ReadOnly Property error_enfermedad_ingresar() As String
            Get
                Return ResourceManager.GetString("error_enfermedad_ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to modify desease..
        '''</summary>
        Friend Shared ReadOnly Property error_enfermedad_modificar() As String
            Get
                Return ResourceManager.GetString("error_enfermedad_modificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name of desease too long..
        '''</summary>
        Friend Shared ReadOnly Property error_enfermedad_nombre_largo() As String
            Get
                Return ResourceManager.GetString("error_enfermedad_nombre_largo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to get the selected desease..
        '''</summary>
        Friend Shared ReadOnly Property error_enfermedad_obtener() As String
            Get
                Return ResourceManager.GetString("error_enfermedad_obtener", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Format Error.
        '''</summary>
        Friend Shared ReadOnly Property error_formato() As String
            Get
                Return ResourceManager.GetString("error_formato", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Incorrect format of  field &apos;Family Antecedents&apos;..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_antecedentes_familiares() As String
            Get
                Return ResourceManager.GetString("error_formato_antecedentes_familiares", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Incorrect format of field &apos;Working Antecedents&apos;..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_antecedentes_laborales() As String
            Get
                Return ResourceManager.GetString("error_formato_antecedentes_laborales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Incorrect format of field &apos;Street&apos;..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_calle() As String
            Get
                Return ResourceManager.GetString("error_formato_calle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ID must be 8 characters long..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_ci_longitud() As String
            Get
                Return ResourceManager.GetString("error_formato_ci_longitud", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ID can only be numbers..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_ci_numerico() As String
            Get
                Return ResourceManager.GetString("error_formato_ci_numerico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Incorrect format of field &apos;Town&apos;..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_localidad() As String
            Get
                Return ResourceManager.GetString("error_formato_localidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Incorrect format of field &apos;Name&apos; ..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_nombre() As String
            Get
                Return ResourceManager.GetString("error_formato_nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Incorrect format of field &apos;Nuclear Family&apos;. .
        '''</summary>
        Friend Shared ReadOnly Property error_formato_nucleo_familiar() As String
            Get
                Return ResourceManager.GetString("error_formato_nucleo_familiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Incorrect format of field &apos;Number&apos;..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_numero() As String
            Get
                Return ResourceManager.GetString("error_formato_numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Phone can only be numbers..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_telefono() As String
            Get
                Return ResourceManager.GetString("error_formato_telefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to seach working hours.
        '''</summary>
        Friend Shared ReadOnly Property error_horario_buscar() As String
            Get
                Return ResourceManager.GetString("error_horario_buscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a We&apos;re sorry. Something went wrong. Please try again!.
        '''</summary>
        Friend Shared ReadOnly Property error_inesperado() As String
            Get
                Return ResourceManager.GetString("error_inesperado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to add the employee..
        '''</summary>
        Friend Shared ReadOnly Property error_ingresar_empleado() As String
            Get
                Return ResourceManager.GetString("error_ingresar_empleado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to modify the employee..
        '''</summary>
        Friend Shared ReadOnly Property error_modificar_empleado() As String
            Get
                Return ResourceManager.GetString("error_modificar_empleado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Can&apos;t modify multiple [ENTIDAD] at once..
        '''</summary>
        Friend Shared ReadOnly Property error_modificar_varios() As String
            Get
                Return ResourceManager.GetString("error_modificar_varios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to get the selected symptoms..
        '''</summary>
        Friend Shared ReadOnly Property error_sintomas_obtener() As String
            Get
                Return ResourceManager.GetString("error_sintomas_obtener", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Speciality.
        '''</summary>
        Friend Shared ReadOnly Property especialidad() As String
            Get
                Return ResourceManager.GetString("especialidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to import from CSV file..
        '''</summary>
        Friend Shared ReadOnly Property ex_csv_file() As String
            Get
                Return ResourceManager.GetString("ex_csv_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Limbs.
        '''</summary>
        Friend Shared ReadOnly Property extremidades() As String
            Get
                Return ResourceManager.GetString("extremidades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Birth Date.
        '''</summary>
        Friend Shared ReadOnly Property fecha_nacimiento() As String
            Get
                Return ResourceManager.GetString("fecha_nacimiento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Filter.
        '''</summary>
        Friend Shared ReadOnly Property filtrar() As String
            Get
                Return ResourceManager.GetString("filtrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CSV files.
        '''</summary>
        Friend Shared ReadOnly Property filtro_csv() As String
            Get
                Return ResourceManager.GetString("filtro_csv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a End Chat.
        '''</summary>
        Friend Shared ReadOnly Property finalizar_chat() As String
            Get
                Return ResourceManager.GetString("finalizar_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Management.
        '''</summary>
        Friend Shared ReadOnly Property gestion() As String
            Get
                Return ResourceManager.GetString("gestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Make Admin.
        '''</summary>
        Friend Shared ReadOnly Property hacer_admin() As String
            Get
                Return ResourceManager.GetString("hacer_admin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clinical History.
        '''</summary>
        Friend Shared ReadOnly Property historial_clinico() As String
            Get
                Return ResourceManager.GetString("historial_clinico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to delete the selected working hours?.
        '''</summary>
        Friend Shared ReadOnly Property horario_eliminar_confirmacion() As String
            Get
                Return ResourceManager.GetString("horario_eliminar_confirmacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Working hours successfully deleted..
        '''</summary>
        Friend Shared ReadOnly Property horario_eliminar_exito() As String
            Get
                Return ResourceManager.GetString("horario_eliminar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Working hours successfully added..
        '''</summary>
        Friend Shared ReadOnly Property horario_ingresar_exito() As String
            Get
                Return ResourceManager.GetString("horario_ingresar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Working hours successfully modified..
        '''</summary>
        Friend Shared ReadOnly Property horario_modificar_exito() As String
            Get
                Return ResourceManager.GetString("horario_modificar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Working Hours.
        '''</summary>
        Friend Shared ReadOnly Property horarios() As String
            Get
                Return ResourceManager.GetString("horarios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Import.
        '''</summary>
        Friend Shared ReadOnly Property importar() As String
            Get
                Return ResourceManager.GetString("importar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Information.
        '''</summary>
        Friend Shared ReadOnly Property informacion() As String
            Get
                Return ResourceManager.GetString("informacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Log In.
        '''</summary>
        Friend Shared ReadOnly Property ingresar() As String
            Get
                Return ResourceManager.GetString("ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Create.
        '''</summary>
        Friend Shared ReadOnly Property ingreso_registro() As String
            Get
                Return ResourceManager.GetString("ingreso_registro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Town.
        '''</summary>
        Friend Shared ReadOnly Property localidad() As String
            Get
                Return ResourceManager.GetString("localidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Doctor.
        '''</summary>
        Friend Shared ReadOnly Property medico() As String
            Get
                Return ResourceManager.GetString("medico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a [NOMBRE_EMPLEADO] is now administrator..
        '''</summary>
        Friend Shared ReadOnly Property mensaje_empleado_ascendido() As String
            Get
                Return ResourceManager.GetString("mensaje_empleado_ascendido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a [COUNT] deleted patients..
        '''</summary>
        Friend Shared ReadOnly Property mensaje_paciente_eliminar() As String
            Get
                Return ResourceManager.GetString("mensaje_paciente_eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modify.
        '''</summary>
        Friend Shared ReadOnly Property modificar() As String
            Get
                Return ResourceManager.GetString("modificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name.
        '''</summary>
        Friend Shared ReadOnly Property nombres() As String
            Get
                Return ResourceManager.GetString("nombres", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nuclear Family.
        '''</summary>
        Friend Shared ReadOnly Property nucleo_familiar() As String
            Get
                Return ResourceManager.GetString("nucleo_familiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New password.
        '''</summary>
        Friend Shared ReadOnly Property nueva_contrasenna() As String
            Get
                Return ResourceManager.GetString("nueva_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Other.
        '''</summary>
        Friend Shared ReadOnly Property otro() As String
            Get
                Return ResourceManager.GetString("otro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a patient.
        '''</summary>
        Friend Shared ReadOnly Property paciente() As String
            Get
                Return ResourceManager.GetString("paciente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paciente successfully added..
        '''</summary>
        Friend Shared ReadOnly Property paciente_ingresar_exito() As String
            Get
                Return ResourceManager.GetString("paciente_ingresar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patient successfully modified..
        '''</summary>
        Friend Shared ReadOnly Property paciente_modificar_exito() As String
            Get
                Return ResourceManager.GetString("paciente_modificar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patients.
        '''</summary>
        Friend Shared ReadOnly Property pacientes() As String
            Get
                Return ResourceManager.GetString("pacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a person.
        '''</summary>
        Friend Shared ReadOnly Property persona() As String
            Get
                Return ResourceManager.GetString("persona", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Working Hours.
        '''</summary>
        Friend Shared ReadOnly Property rango_horario() As String
            Get
                Return ResourceManager.GetString("rango_horario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Receptionist.
        '''</summary>
        Friend Shared ReadOnly Property recepcionista() As String
            Get
                Return ResourceManager.GetString("recepcionista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Human Resources.
        '''</summary>
        Friend Shared ReadOnly Property recursos_humanos() As String
            Get
                Return ResourceManager.GetString("recursos_humanos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reset Password.
        '''</summary>
        Friend Shared ReadOnly Property restablecer_contrasenna() As String
            Get
                Return ResourceManager.GetString("restablecer_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Role.
        '''</summary>
        Friend Shared ReadOnly Property rol() As String
            Get
                Return ResourceManager.GetString("rol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sex.
        '''</summary>
        Friend Shared ReadOnly Property sexo() As String
            Get
                Return ResourceManager.GetString("sexo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptom.
        '''</summary>
        Friend Shared ReadOnly Property sintoma() As String
            Get
                Return ResourceManager.GetString("sintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a [COUNT] deleted symptoms..
        '''</summary>
        Friend Shared ReadOnly Property sintoma_eliminar_exito() As String
            Get
                Return ResourceManager.GetString("sintoma_eliminar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptoms successfully imported..
        '''</summary>
        Friend Shared ReadOnly Property sintoma_import_exito() As String
            Get
                Return ResourceManager.GetString("sintoma_import_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptom successfully added..
        '''</summary>
        Friend Shared ReadOnly Property sintoma_ingresar_exito() As String
            Get
                Return ResourceManager.GetString("sintoma_ingresar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symtom successfully modified..
        '''</summary>
        Friend Shared ReadOnly Property sintoma_modificar_exito() As String
            Get
                Return ResourceManager.GetString("sintoma_modificar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property sintomas() As String
            Get
                Return ResourceManager.GetString("sintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Given Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property sintomas_ingresados() As String
            Get
                Return ResourceManager.GetString("sintomas_ingresados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Given Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property sintomas_registrados() As String
            Get
                Return ResourceManager.GetString("sintomas_registrados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a office.
        '''</summary>
        Friend Shared ReadOnly Property sucursal() As String
            Get
                Return ResourceManager.GetString("sucursal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Office.
        '''</summary>
        Friend Shared ReadOnly Property sucursales() As String
            Get
                Return ResourceManager.GetString("sucursales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Phone.
        '''</summary>
        Friend Shared ReadOnly Property telefono() As String
            Get
                Return ResourceManager.GetString("telefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Type.
        '''</summary>
        Friend Shared ReadOnly Property tipo_enfermedad() As String
            Get
                Return ResourceManager.GetString("tipo_enfermedad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tipo.
        '''</summary>
        Friend Shared ReadOnly Property tipo_sintoma() As String
            Get
                Return ResourceManager.GetString("tipo_sintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Added Employee.
        '''</summary>
        Friend Shared ReadOnly Property titulo_empleado_ingresado() As String
            Get
                Return ResourceManager.GetString("titulo_empleado_ingresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User Added.
        '''</summary>
        Friend Shared ReadOnly Property titulo_usuario_ingresado() As String
            Get
                Return ResourceManager.GetString("titulo_usuario_ingresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a All.
        '''</summary>
        Friend Shared ReadOnly Property todo() As String
            Get
                Return ResourceManager.GetString("todo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Torso.
        '''</summary>
        Friend Shared ReadOnly Property torso() As String
            Get
                Return ResourceManager.GetString("torso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Urgency.
        '''</summary>
        Friend Shared ReadOnly Property urgencia() As String
            Get
                Return ResourceManager.GetString("urgencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Back.
        '''</summary>
        Friend Shared ReadOnly Property volver() As String
            Get
                Return ResourceManager.GetString("volver", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
