'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class es_UY
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Presentacion.es-UY", GetType(es_UY).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error.
        '''</summary>
        Friend Shared ReadOnly Property _error() As String
            Get
                Return ResourceManager.GetString("error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Acceso denegado.
        '''</summary>
        Friend Shared ReadOnly Property acceso_denegado() As String
            Get
                Return ResourceManager.GetString("acceso_denegado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aceptar.
        '''</summary>
        Friend Shared ReadOnly Property aceptar() As String
            Get
                Return ResourceManager.GetString("aceptar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antecedentes Familiares.
        '''</summary>
        Friend Shared ReadOnly Property antecedentes_familiares() As String
            Get
                Return ResourceManager.GetString("antecedentes_familiares", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antecedentes Laborales.
        '''</summary>
        Friend Shared ReadOnly Property antecedentes_laborales() As String
            Get
                Return ResourceManager.GetString("antecedentes_laborales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Apellidos.
        '''</summary>
        Friend Shared ReadOnly Property apellidos() As String
            Get
                Return ResourceManager.GetString("apellidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Autenticación.
        '''</summary>
        Friend Shared ReadOnly Property autenticacion() As String
            Get
                Return ResourceManager.GetString("autenticacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Busqueda.
        '''</summary>
        Friend Shared ReadOnly Property busqueda() As String
            Get
                Return ResourceManager.GetString("busqueda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cabeza.
        '''</summary>
        Friend Shared ReadOnly Property cabeza() As String
            Get
                Return ResourceManager.GetString("cabeza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Calle.
        '''</summary>
        Friend Shared ReadOnly Property calle() As String
            Get
                Return ResourceManager.GetString("calle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancelar.
        '''</summary>
        Friend Shared ReadOnly Property cancelar() As String
            Get
                Return ResourceManager.GetString("cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cerrar Sesión.
        '''</summary>
        Friend Shared ReadOnly Property cerrar_sesion() As String
            Get
                Return ResourceManager.GetString("cerrar_sesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CI.
        '''</summary>
        Friend Shared ReadOnly Property ci() As String
            Get
                Return ResourceManager.GetString("ci", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirmación.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion() As String
            Get
                Return ResourceManager.GetString("confirmacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está seguro que desea cambiar su cambiar su contraseña?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_cambiar_contrasenna() As String
            Get
                Return ResourceManager.GetString("confirmacion_cambiar_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está seguro de que desea cerrar sesión?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_cerrar_sesion() As String
            Get
                Return ResourceManager.GetString("confirmacion_cerrar_sesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está seguro de que desea finalizar el chat?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_finalizar_chat() As String
            Get
                Return ResourceManager.GetString("confirmacion_finalizar_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Desea establecer un chat con un médico para obtener un diagnóstico más certero?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_iniciar_chat() As String
            Get
                Return ResourceManager.GetString("confirmacion_iniciar_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está seguro de que desea eliminar los pacientes seleccionados?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_paciente_eliminar() As String
            Get
                Return ResourceManager.GetString("confirmacion_paciente_eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está seguro de que desea eliminar el síntoma seleccionado?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_sintoma_eliminar() As String
            Get
                Return ResourceManager.GetString("confirmacion_sintoma_eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está seguro de que desea eliminar los [COUNT] sintomas seleccionados?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_sintoma_eliminar_varios() As String
            Get
                Return ResourceManager.GetString("confirmacion_sintoma_eliminar_varios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirmar nueva nontraseña.
        '''</summary>
        Friend Shared ReadOnly Property confirmar_nueva_contrasenna() As String
            Get
                Return ResourceManager.GetString("confirmar_nueva_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contraseña.
        '''</summary>
        Friend Shared ReadOnly Property contrasenna() As String
            Get
                Return ResourceManager.GetString("contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se detectó una contraseña autogenerada.
        '''</summary>
        Friend Shared ReadOnly Property contrasenna_autogenerada_detectada() As String
            Get
                Return ResourceManager.GetString("contrasenna_autogenerada_detectada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contraseña cambiada con éxito.
        '''</summary>
        Friend Shared ReadOnly Property contrasenna_cambiada_exito() As String
            Get
                Return ResourceManager.GetString("contrasenna_cambiada_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Crónica.
        '''</summary>
        Friend Shared ReadOnly Property cronica() As String
            Get
                Return ResourceManager.GetString("cronica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cualquiera.
        '''</summary>
        Friend Shared ReadOnly Property cualquiera() As String
            Get
                Return ResourceManager.GetString("cualquiera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Departamento.
        '''</summary>
        Friend Shared ReadOnly Property departamento() As String
            Get
                Return ResourceManager.GetString("departamento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descripción.
        '''</summary>
        Friend Shared ReadOnly Property descripcion() As String
            Get
                Return ResourceManager.GetString("descripcion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Detalles.
        '''</summary>
        Friend Shared ReadOnly Property detalles() As String
            Get
                Return ResourceManager.GetString("detalles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a D.
        '''</summary>
        Friend Shared ReadOnly Property dia_domingo() As String
            Get
                Return ResourceManager.GetString("dia_domingo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a J.
        '''</summary>
        Friend Shared ReadOnly Property dia_jueves() As String
            Get
                Return ResourceManager.GetString("dia_jueves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a L.
        '''</summary>
        Friend Shared ReadOnly Property dia_lunes() As String
            Get
                Return ResourceManager.GetString("dia_lunes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a M.
        '''</summary>
        Friend Shared ReadOnly Property dia_martes() As String
            Get
                Return ResourceManager.GetString("dia_martes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a X.
        '''</summary>
        Friend Shared ReadOnly Property dia_miercoles() As String
            Get
                Return ResourceManager.GetString("dia_miercoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a S.
        '''</summary>
        Friend Shared ReadOnly Property dia_sabado() As String
            Get
                Return ResourceManager.GetString("dia_sabado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnóstico.
        '''</summary>
        Friend Shared ReadOnly Property diagnostico() As String
            Get
                Return ResourceManager.GetString("diagnostico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Los sintomas provistos concluyeron en un diagnóstico demasiado ambiguo. Por favor trate de ser lo más específico posible..
        '''</summary>
        Friend Shared ReadOnly Property diagnostico_ambiguo() As String
            Get
                Return ResourceManager.GetString("diagnostico_ambiguo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se diagnosticaron las siguientes enfermedades:.
        '''</summary>
        Friend Shared ReadOnly Property diagnostico_primario_mensaje_salida_1() As String
            Get
                Return ResourceManager.GetString("diagnostico_primario_mensaje_salida_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recuerde que solamente es un diagnóstico primario..
        '''</summary>
        Friend Shared ReadOnly Property diagnostico_primario_mensaje_salida_2() As String
            Get
                Return ResourceManager.GetString("diagnostico_primario_mensaje_salida_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Días.
        '''</summary>
        Friend Shared ReadOnly Property dias() As String
            Get
                Return ResourceManager.GetString("dias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dirección.
        '''</summary>
        Friend Shared ReadOnly Property direccion() As String
            Get
                Return ResourceManager.GetString("direccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Número.
        '''</summary>
        Friend Shared ReadOnly Property direccion_numero() As String
            Get
                Return ResourceManager.GetString("direccion_numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Edad.
        '''</summary>
        Friend Shared ReadOnly Property edad() As String
            Get
                Return ResourceManager.GetString("edad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Eliminar.
        '''</summary>
        Friend Shared ReadOnly Property eliminar() As String
            Get
                Return ResourceManager.GetString("eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email.
        '''</summary>
        Friend Shared ReadOnly Property email() As String
            Get
                Return ResourceManager.GetString("email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Empleado.
        '''</summary>
        Friend Shared ReadOnly Property empleado() As String
            Get
                Return ResourceManager.GetString("empleado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a [TIPO_EMPLEADO] ingresado con éxito..
        '''</summary>
        Friend Shared ReadOnly Property empleado_ingresado_exito() As String
            Get
                Return ResourceManager.GetString("empleado_ingresado_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Empleado modificado con éxito..
        '''</summary>
        Friend Shared ReadOnly Property empleado_modificado_exito() As String
            Get
                Return ResourceManager.GetString("empleado_modificado_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Empleados.
        '''</summary>
        Friend Shared ReadOnly Property empleados() As String
            Get
                Return ResourceManager.GetString("empleados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a empleados eliminados exitosamente..
        '''</summary>
        Friend Shared ReadOnly Property empleados_eliminados_exito() As String
            Get
                Return ResourceManager.GetString("empleados_eliminados_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enfermedad.
        '''</summary>
        Friend Shared ReadOnly Property enfermedad() As String
            Get
                Return ResourceManager.GetString("enfermedad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enfermedades importadas con éxito..
        '''</summary>
        Friend Shared ReadOnly Property enfermedad_import_exito() As String
            Get
                Return ResourceManager.GetString("enfermedad_import_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enfermedad ingresada con éxito..
        '''</summary>
        Friend Shared ReadOnly Property enfermedad_ingresada_exito() As String
            Get
                Return ResourceManager.GetString("enfermedad_ingresada_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enfermedad modificada con éxito..
        '''</summary>
        Friend Shared ReadOnly Property enfermedad_modificada_exito() As String
            Get
                Return ResourceManager.GetString("enfermedad_modificada_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enfermedades.
        '''</summary>
        Friend Shared ReadOnly Property enfermedades() As String
            Get
                Return ResourceManager.GetString("enfermedades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está seguro que desea eliminar las enfermedades seleccionadas?.
        '''</summary>
        Friend Shared ReadOnly Property enfermedades_eliminar_confirmacion() As String
            Get
                Return ResourceManager.GetString("enfermedades_eliminar_confirmacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se pudo actualizar la contraseña..
        '''</summary>
        Friend Shared ReadOnly Property error_actualizar_contrasenna() As String
            Get
                Return ResourceManager.GetString("error_actualizar_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Solo los médicos pueden ser administradores..
        '''</summary>
        Friend Shared ReadOnly Property error_ascender_no_medico() As String
            Get
                Return ResourceManager.GetString("error_ascender_no_medico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se puede hacer administrado a más de un médico a la vez..
        '''</summary>
        Friend Shared ReadOnly Property error_ascender_varios() As String
            Get
                Return ResourceManager.GetString("error_ascender_varios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Por favor ingrese por lo menos un apellido..
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_apellidos() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_apellidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El campo calle es obligatorio..
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_calle() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_calle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El campo cédula es obligatorio..
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_ci() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_ci", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El campo localidad es obligatorio..
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_localidad() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_localidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El campo nombre es obligatorio..
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_nombre() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El nombre del síntoma no puede ser vacío..
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_nombre_sintoma() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_nombre_sintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El campo número es obligatorio..
        '''</summary>
        Friend Shared ReadOnly Property error_campo_obligatorio_numero() As String
            Get
                Return ResourceManager.GetString("error_campo_obligatorio_numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La cédula ingresada no es válida..
        '''</summary>
        Friend Shared ReadOnly Property error_ci_invalida() As String
            Get
                Return ResourceManager.GetString("error_ci_invalida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CI y/o contraseña incorrecta..
        '''</summary>
        Friend Shared ReadOnly Property error_credenciales_incorrectas() As String
            Get
                Return ResourceManager.GetString("error_credenciales_incorrectas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al eliminar el empleado..
        '''</summary>
        Friend Shared ReadOnly Property error_eliminar_empleado() As String
            Get
                Return ResourceManager.GetString("error_eliminar_empleado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se pudo eliminar la persona.
        '''</summary>
        Friend Shared ReadOnly Property error_eliminar_persona() As String
            Get
                Return ResourceManager.GetString("error_eliminar_persona", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al eliminar la enfermedad [NOMBRE_ENFERMEDAD] .
        '''</summary>
        Friend Shared ReadOnly Property error_enfermedad_eliminar() As String
            Get
                Return ResourceManager.GetString("error_enfermedad_eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al ingresar la enfermedad.
        '''</summary>
        Friend Shared ReadOnly Property error_enfermedad_ingresar() As String
            Get
                Return ResourceManager.GetString("error_enfermedad_ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se pudo modificar la enfermedad..
        '''</summary>
        Friend Shared ReadOnly Property error_enfermedad_modificar() As String
            Get
                Return ResourceManager.GetString("error_enfermedad_modificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al obtener las enfermedades seleccionadas..
        '''</summary>
        Friend Shared ReadOnly Property error_enfermedad_obtener() As String
            Get
                Return ResourceManager.GetString("error_enfermedad_obtener", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se pudo enviar el mensaje..
        '''</summary>
        Friend Shared ReadOnly Property error_enviar_mensaje() As String
            Get
                Return ResourceManager.GetString("error_enviar_mensaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error de Formato.
        '''</summary>
        Friend Shared ReadOnly Property error_formato() As String
            Get
                Return ResourceManager.GetString("error_formato", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El formato del campo antecedentes familiares no es correcto..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_antecedentes_familiares() As String
            Get
                Return ResourceManager.GetString("error_formato_antecedentes_familiares", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El formato del campo antecedentes laborales no es correcto..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_antecedentes_laborales() As String
            Get
                Return ResourceManager.GetString("error_formato_antecedentes_laborales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El formato del campo calle no es correcto..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_calle() As String
            Get
                Return ResourceManager.GetString("error_formato_calle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La cédula de identidad debe tener una longitud de 8 dígitos..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_ci_longitud() As String
            Get
                Return ResourceManager.GetString("error_formato_ci_longitud", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La cédula de identidad solo puede contener dígitos..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_ci_numerico() As String
            Get
                Return ResourceManager.GetString("error_formato_ci_numerico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El formato del campo localidad no es correcto..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_localidad() As String
            Get
                Return ResourceManager.GetString("error_formato_localidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El formato del campo nombre no es correcto..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_nombre() As String
            Get
                Return ResourceManager.GetString("error_formato_nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El formato del campo núcleo familiar no es correcto..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_nucleo_familiar() As String
            Get
                Return ResourceManager.GetString("error_formato_nucleo_familiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El formato del campo número no es correcto..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_numero() As String
            Get
                Return ResourceManager.GetString("error_formato_numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El teléfono solo puede contener dígitos numéricos..
        '''</summary>
        Friend Shared ReadOnly Property error_formato_telefono() As String
            Get
                Return ResourceManager.GetString("error_formato_telefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al buscar horarios..
        '''</summary>
        Friend Shared ReadOnly Property error_horario_buscar() As String
            Get
                Return ResourceManager.GetString("error_horario_buscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Lo lamentamos. Ha ocurrido un error. Por favor ¡intente de nuevo!.
        '''</summary>
        Friend Shared ReadOnly Property error_inesperado() As String
            Get
                Return ResourceManager.GetString("error_inesperado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al ingresar el empleado..
        '''</summary>
        Friend Shared ReadOnly Property error_ingresar_empleado() As String
            Get
                Return ResourceManager.GetString("error_ingresar_empleado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se pudo ingresar la persona..
        '''</summary>
        Friend Shared ReadOnly Property error_ingresar_persona() As String
            Get
                Return ResourceManager.GetString("error_ingresar_persona", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al modificar el empleado..
        '''</summary>
        Friend Shared ReadOnly Property error_modificar_empleado() As String
            Get
                Return ResourceManager.GetString("error_modificar_empleado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al modificar la persona..
        '''</summary>
        Friend Shared ReadOnly Property error_modificar_persona() As String
            Get
                Return ResourceManager.GetString("error_modificar_persona", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se puede modificar más de un [ENTIDAD] a la vez..
        '''</summary>
        Friend Shared ReadOnly Property error_modificar_varios() As String
            Get
                Return ResourceManager.GetString("error_modificar_varios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al obtener el empleado..
        '''</summary>
        Friend Shared ReadOnly Property error_obtener_empleado() As String
            Get
                Return ResourceManager.GetString("error_obtener_empleado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se pudieron obtener los síntomas seleccionados..
        '''</summary>
        Friend Shared ReadOnly Property error_sintomas_obtener() As String
            Get
                Return ResourceManager.GetString("error_sintomas_obtener", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Especialidad.
        '''</summary>
        Friend Shared ReadOnly Property especialidad() As String
            Get
                Return ResourceManager.GetString("especialidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al importar desde archivo CSV..
        '''</summary>
        Friend Shared ReadOnly Property ex_csv_file() As String
            Get
                Return ResourceManager.GetString("ex_csv_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Extremidades.
        '''</summary>
        Friend Shared ReadOnly Property extremidades() As String
            Get
                Return ResourceManager.GetString("extremidades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha de Nacimiento.
        '''</summary>
        Friend Shared ReadOnly Property fecha_nacimiento() As String
            Get
                Return ResourceManager.GetString("fecha_nacimiento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Filtrar.
        '''</summary>
        Friend Shared ReadOnly Property filtrar() As String
            Get
                Return ResourceManager.GetString("filtrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Archivos CSV.
        '''</summary>
        Friend Shared ReadOnly Property filtro_csv() As String
            Get
                Return ResourceManager.GetString("filtro_csv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gestión.
        '''</summary>
        Friend Shared ReadOnly Property gestion() As String
            Get
                Return ResourceManager.GetString("gestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hacer Admin.
        '''</summary>
        Friend Shared ReadOnly Property hacer_admin() As String
            Get
                Return ResourceManager.GetString("hacer_admin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Historial Clínico.
        '''</summary>
        Friend Shared ReadOnly Property historial_clinico() As String
            Get
                Return ResourceManager.GetString("historial_clinico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está seguro que desea eliminar los horarios seleccionados?.
        '''</summary>
        Friend Shared ReadOnly Property horario_eliminar_confirmacion() As String
            Get
                Return ResourceManager.GetString("horario_eliminar_confirmacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Horarios eliminados con éxito..
        '''</summary>
        Friend Shared ReadOnly Property horario_eliminar_exito() As String
            Get
                Return ResourceManager.GetString("horario_eliminar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Horario ingresado con éxito..
        '''</summary>
        Friend Shared ReadOnly Property horario_ingresar_exito() As String
            Get
                Return ResourceManager.GetString("horario_ingresar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Horario modificado con éxito..
        '''</summary>
        Friend Shared ReadOnly Property horario_modificar_exito() As String
            Get
                Return ResourceManager.GetString("horario_modificar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Horarios.
        '''</summary>
        Friend Shared ReadOnly Property horarios() As String
            Get
                Return ResourceManager.GetString("horarios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Importar.
        '''</summary>
        Friend Shared ReadOnly Property importar() As String
            Get
                Return ResourceManager.GetString("importar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Información.
        '''</summary>
        Friend Shared ReadOnly Property informacion() As String
            Get
                Return ResourceManager.GetString("informacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingresar.
        '''</summary>
        Friend Shared ReadOnly Property ingresar() As String
            Get
                Return ResourceManager.GetString("ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingresar.
        '''</summary>
        Friend Shared ReadOnly Property ingreso_registro() As String
            Get
                Return ResourceManager.GetString("ingreso_registro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Localidad.
        '''</summary>
        Friend Shared ReadOnly Property localidad() As String
            Get
                Return ResourceManager.GetString("localidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Médico.
        '''</summary>
        Friend Shared ReadOnly Property medico() As String
            Get
                Return ResourceManager.GetString("medico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a [NOMBRE_EMPLEADO] ascendido a administrador..
        '''</summary>
        Friend Shared ReadOnly Property mensaje_empleado_ascendido() As String
            Get
                Return ResourceManager.GetString("mensaje_empleado_ascendido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a [COUNT] pacientes eliminados..
        '''</summary>
        Friend Shared ReadOnly Property mensaje_paciente_eliminar() As String
            Get
                Return ResourceManager.GetString("mensaje_paciente_eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificar.
        '''</summary>
        Friend Shared ReadOnly Property modificar() As String
            Get
                Return ResourceManager.GetString("modificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombres.
        '''</summary>
        Friend Shared ReadOnly Property nombres() As String
            Get
                Return ResourceManager.GetString("nombres", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Núcleo Familiar.
        '''</summary>
        Friend Shared ReadOnly Property nucleo_familiar() As String
            Get
                Return ResourceManager.GetString("nucleo_familiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nueva contraseña.
        '''</summary>
        Friend Shared ReadOnly Property nueva_contrasenna() As String
            Get
                Return ResourceManager.GetString("nueva_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Otro.
        '''</summary>
        Friend Shared ReadOnly Property otro() As String
            Get
                Return ResourceManager.GetString("otro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a paciente.
        '''</summary>
        Friend Shared ReadOnly Property paciente() As String
            Get
                Return ResourceManager.GetString("paciente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paciente ingresado con éxito..
        '''</summary>
        Friend Shared ReadOnly Property paciente_ingresar_exito() As String
            Get
                Return ResourceManager.GetString("paciente_ingresar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paciente modificado con éxito..
        '''</summary>
        Friend Shared ReadOnly Property paciente_modificar_exito() As String
            Get
                Return ResourceManager.GetString("paciente_modificar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pacientes.
        '''</summary>
        Friend Shared ReadOnly Property pacientes() As String
            Get
                Return ResourceManager.GetString("pacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a persona.
        '''</summary>
        Friend Shared ReadOnly Property persona() As String
            Get
                Return ResourceManager.GetString("persona", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Rango Horario.
        '''</summary>
        Friend Shared ReadOnly Property rango_horario() As String
            Get
                Return ResourceManager.GetString("rango_horario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recepcionista.
        '''</summary>
        Friend Shared ReadOnly Property recepcionista() As String
            Get
                Return ResourceManager.GetString("recepcionista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recursos Humanos.
        '''</summary>
        Friend Shared ReadOnly Property recursos_humanos() As String
            Get
                Return ResourceManager.GetString("recursos_humanos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Restablecer Contraseña.
        '''</summary>
        Friend Shared ReadOnly Property restablecer_contrasenna() As String
            Get
                Return ResourceManager.GetString("restablecer_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Rol.
        '''</summary>
        Friend Shared ReadOnly Property rol() As String
            Get
                Return ResourceManager.GetString("rol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sexo.
        '''</summary>
        Friend Shared ReadOnly Property sexo() As String
            Get
                Return ResourceManager.GetString("sexo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntoma.
        '''</summary>
        Friend Shared ReadOnly Property sintoma() As String
            Get
                Return ResourceManager.GetString("sintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a [COUNT] síntomas eliminados..
        '''</summary>
        Friend Shared ReadOnly Property sintoma_eliminar_exito() As String
            Get
                Return ResourceManager.GetString("sintoma_eliminar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sintomas importados con éxito..
        '''</summary>
        Friend Shared ReadOnly Property sintoma_import_exito() As String
            Get
                Return ResourceManager.GetString("sintoma_import_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sintoma ingresado correctamente..
        '''</summary>
        Friend Shared ReadOnly Property sintoma_ingresar_exito() As String
            Get
                Return ResourceManager.GetString("sintoma_ingresar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sintoma modificado correctamente..
        '''</summary>
        Friend Shared ReadOnly Property sintoma_modificar_exito() As String
            Get
                Return ResourceManager.GetString("sintoma_modificar_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntomas.
        '''</summary>
        Friend Shared ReadOnly Property sintomas() As String
            Get
                Return ResourceManager.GetString("sintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntomas Ingresados.
        '''</summary>
        Friend Shared ReadOnly Property sintomas_ingresados() As String
            Get
                Return ResourceManager.GetString("sintomas_ingresados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntomas Registrados.
        '''</summary>
        Friend Shared ReadOnly Property sintomas_registrados() As String
            Get
                Return ResourceManager.GetString("sintomas_registrados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sucursal.
        '''</summary>
        Friend Shared ReadOnly Property sucursal() As String
            Get
                Return ResourceManager.GetString("sucursal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sucursales.
        '''</summary>
        Friend Shared ReadOnly Property sucursales() As String
            Get
                Return ResourceManager.GetString("sucursales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Telefono.
        '''</summary>
        Friend Shared ReadOnly Property telefono() As String
            Get
                Return ResourceManager.GetString("telefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tipo.
        '''</summary>
        Friend Shared ReadOnly Property tipo_enfermedad() As String
            Get
                Return ResourceManager.GetString("tipo_enfermedad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tipo.
        '''</summary>
        Friend Shared ReadOnly Property tipo_sintoma() As String
            Get
                Return ResourceManager.GetString("tipo_sintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Eliminación de Empleados.
        '''</summary>
        Friend Shared ReadOnly Property titulo_eliminar_empleado() As String
            Get
                Return ResourceManager.GetString("titulo_eliminar_empleado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Empleado Ingresado.
        '''</summary>
        Friend Shared ReadOnly Property titulo_empleado_ingresado() As String
            Get
                Return ResourceManager.GetString("titulo_empleado_ingresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario Agregado.
        '''</summary>
        Friend Shared ReadOnly Property titulo_usuario_ingresado() As String
            Get
                Return ResourceManager.GetString("titulo_usuario_ingresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Todo.
        '''</summary>
        Friend Shared ReadOnly Property todo() As String
            Get
                Return ResourceManager.GetString("todo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Torso.
        '''</summary>
        Friend Shared ReadOnly Property torso() As String
            Get
                Return ResourceManager.GetString("torso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Urgencia.
        '''</summary>
        Friend Shared ReadOnly Property urgencia() As String
            Get
                Return ResourceManager.GetString("urgencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Volver.
        '''</summary>
        Friend Shared ReadOnly Property volver() As String
            Get
                Return ResourceManager.GetString("volver", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
