'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class en_US
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Medico_Presentacion.en-US", GetType(en_US).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error.
        '''</summary>
        Friend Shared ReadOnly Property _error() As String
            Get
                Return ResourceManager.GetString("error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Accept.
        '''</summary>
        Friend Shared ReadOnly Property aceptar() As String
            Get
                Return ResourceManager.GetString("aceptar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Years old.
        '''</summary>
        Friend Shared ReadOnly Property annos() As String
            Get
                Return ResourceManager.GetString("annos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Authentication.
        '''</summary>
        Friend Shared ReadOnly Property autenticacion() As String
            Get
                Return ResourceManager.GetString("autenticacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property cancelar() As String
            Get
                Return ResourceManager.GetString("cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Close Session.
        '''</summary>
        Friend Shared ReadOnly Property cerrar_sesion() As String
            Get
                Return ResourceManager.GetString("cerrar_sesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ID.
        '''</summary>
        Friend Shared ReadOnly Property ci() As String
            Get
                Return ResourceManager.GetString("ci", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirmation.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion() As String
            Get
                Return ResourceManager.GetString("confirmacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to change your password?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_cambiar_contrasenna() As String
            Get
                Return ResourceManager.GetString("confirmacion_cambiar_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to close your session?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_cerrar_sesion() As String
            Get
                Return ResourceManager.GetString("confirmacion_cerrar_sesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to end the chat with the patient [NOMBRE_PACIENTE]?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_finalizar_chat() As String
            Get
                Return ResourceManager.GetString("confirmacion_finalizar_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you wanto to have a chat with the selected patient?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_iniciar_chat() As String
            Get
                Return ResourceManager.GetString("confirmacion_iniciar_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirm new password.
        '''</summary>
        Friend Shared ReadOnly Property confirmar_nueva_contrasenna() As String
            Get
                Return ResourceManager.GetString("confirmar_nueva_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Appointment ended.
        '''</summary>
        Friend Shared ReadOnly Property consulta_finalizada() As String
            Get
                Return ResourceManager.GetString("consulta_finalizada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password.
        '''</summary>
        Friend Shared ReadOnly Property contrasenna() As String
            Get
                Return ResourceManager.GetString("contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Autogenerated password detected.
        '''</summary>
        Friend Shared ReadOnly Property contrasenna_autogenerada_detectada() As String
            Get
                Return ResourceManager.GetString("contrasenna_autogenerada_detectada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password changed succesfully.
        '''</summary>
        Friend Shared ReadOnly Property contrasenna_cambiada_exito() As String
            Get
                Return ResourceManager.GetString("contrasenna_cambiada_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnosis.
        '''</summary>
        Friend Shared ReadOnly Property diagnostico() As String
            Get
                Return ResourceManager.GetString("diagnostico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to generate chat copy..
        '''</summary>
        Friend Shared ReadOnly Property error_copia_chat() As String
            Get
                Return ResourceManager.GetString("error_copia_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Incorrect ID or password.
        '''</summary>
        Friend Shared ReadOnly Property error_credenciales_incorrectas() As String
            Get
                Return ResourceManager.GetString("error_credenciales_incorrectas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to send the message..
        '''</summary>
        Friend Shared ReadOnly Property error_enviar_mensaje() As String
            Get
                Return ResourceManager.GetString("error_enviar_mensaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a End Chat.
        '''</summary>
        Friend Shared ReadOnly Property finalizar_chat() As String
            Get
                Return ResourceManager.GetString("finalizar_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clinical History.
        '''</summary>
        Friend Shared ReadOnly Property historial_clinico() As String
            Get
                Return ResourceManager.GetString("historial_clinico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Information.
        '''</summary>
        Friend Shared ReadOnly Property informacion() As String
            Get
                Return ResourceManager.GetString("informacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Log In.
        '''</summary>
        Friend Shared ReadOnly Property ingresar() As String
            Get
                Return ResourceManager.GetString("ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Doctor.
        '''</summary>
        Friend Shared ReadOnly Property medico() As String
            Get
                Return ResourceManager.GetString("medico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The chat with the doctor has ended.
        '''</summary>
        Friend Shared ReadOnly Property mensaje_chat_finalizado() As String
            Get
                Return ResourceManager.GetString("mensaje_chat_finalizado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New password.
        '''</summary>
        Friend Shared ReadOnly Property nueva_contrasenna() As String
            Get
                Return ResourceManager.GetString("nueva_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Possible Diagnosis.
        '''</summary>
        Friend Shared ReadOnly Property posibles_diagnosticos() As String
            Get
                Return ResourceManager.GetString("posibles_diagnosticos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reset Password.
        '''</summary>
        Friend Shared ReadOnly Property restablecer_contrasenna() As String
            Get
                Return ResourceManager.GetString("restablecer_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Given Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property sintomas_ingresados() As String
            Get
                Return ResourceManager.GetString("sintomas_ingresados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Given Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property sintomas_registrados() As String
            Get
                Return ResourceManager.GetString("sintomas_registrados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat Ended.
        '''</summary>
        Friend Shared ReadOnly Property titulo_chat_finalizado() As String
            Get
                Return ResourceManager.GetString("titulo_chat_finalizado", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
