'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class es_UY
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Medico_Presentacion.es-UY", GetType(es_UY).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error.
        '''</summary>
        Friend Shared ReadOnly Property _error() As String
            Get
                Return ResourceManager.GetString("error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aceptar.
        '''</summary>
        Friend Shared ReadOnly Property aceptar() As String
            Get
                Return ResourceManager.GetString("aceptar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Años.
        '''</summary>
        Friend Shared ReadOnly Property annos() As String
            Get
                Return ResourceManager.GetString("annos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Autenticación.
        '''</summary>
        Friend Shared ReadOnly Property autenticacion() As String
            Get
                Return ResourceManager.GetString("autenticacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancelar.
        '''</summary>
        Friend Shared ReadOnly Property cancelar() As String
            Get
                Return ResourceManager.GetString("cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cerrar Sesión.
        '''</summary>
        Friend Shared ReadOnly Property cerrar_sesion() As String
            Get
                Return ResourceManager.GetString("cerrar_sesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CI.
        '''</summary>
        Friend Shared ReadOnly Property ci() As String
            Get
                Return ResourceManager.GetString("ci", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirmación.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion() As String
            Get
                Return ResourceManager.GetString("confirmacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está seguro que desea cambiar su cambiar su contraseña?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_cambiar_contrasenna() As String
            Get
                Return ResourceManager.GetString("confirmacion_cambiar_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está seguro de que desea cerrar sesión?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_cerrar_sesion() As String
            Get
                Return ResourceManager.GetString("confirmacion_cerrar_sesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está seguro de que desea finalizar el chat con el paciente [NOMBRE_PACIENTE] ?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_finalizar_chat() As String
            Get
                Return ResourceManager.GetString("confirmacion_finalizar_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está seguro de que desea iniciar el chat con el paciente seleccionado?.
        '''</summary>
        Friend Shared ReadOnly Property confirmacion_iniciar_chat() As String
            Get
                Return ResourceManager.GetString("confirmacion_iniciar_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirmar nueva nontraseña.
        '''</summary>
        Friend Shared ReadOnly Property confirmar_nueva_contrasenna() As String
            Get
                Return ResourceManager.GetString("confirmar_nueva_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Consulta Finalizada.
        '''</summary>
        Friend Shared ReadOnly Property consulta_finalizada() As String
            Get
                Return ResourceManager.GetString("consulta_finalizada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contraseña.
        '''</summary>
        Friend Shared ReadOnly Property contrasenna() As String
            Get
                Return ResourceManager.GetString("contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se detectó una contraseña autogenerada.
        '''</summary>
        Friend Shared ReadOnly Property contrasenna_autogenerada_detectada() As String
            Get
                Return ResourceManager.GetString("contrasenna_autogenerada_detectada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contraseña cambiada con éxito.
        '''</summary>
        Friend Shared ReadOnly Property contrasenna_cambiada_exito() As String
            Get
                Return ResourceManager.GetString("contrasenna_cambiada_exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnóstico.
        '''</summary>
        Friend Shared ReadOnly Property diagnostico() As String
            Get
                Return ResourceManager.GetString("diagnostico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se ha podido generar la copia del chat..
        '''</summary>
        Friend Shared ReadOnly Property error_copia_chat() As String
            Get
                Return ResourceManager.GetString("error_copia_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CI y/o contraseña incorrecta..
        '''</summary>
        Friend Shared ReadOnly Property error_credenciales_incorrectas() As String
            Get
                Return ResourceManager.GetString("error_credenciales_incorrectas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se pudo enviar el mensaje..
        '''</summary>
        Friend Shared ReadOnly Property error_enviar_mensaje() As String
            Get
                Return ResourceManager.GetString("error_enviar_mensaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Extremidades.
        '''</summary>
        Friend Shared ReadOnly Property extremidades() As String
            Get
                Return ResourceManager.GetString("extremidades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Finalizar Chat.
        '''</summary>
        Friend Shared ReadOnly Property finalizar_chat() As String
            Get
                Return ResourceManager.GetString("finalizar_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Historial Clínico.
        '''</summary>
        Friend Shared ReadOnly Property historial_clinico() As String
            Get
                Return ResourceManager.GetString("historial_clinico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Información.
        '''</summary>
        Friend Shared ReadOnly Property informacion() As String
            Get
                Return ResourceManager.GetString("informacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingresar.
        '''</summary>
        Friend Shared ReadOnly Property ingresar() As String
            Get
                Return ResourceManager.GetString("ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Médico.
        '''</summary>
        Friend Shared ReadOnly Property medico() As String
            Get
                Return ResourceManager.GetString("medico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El chat con el médico ha finalizado..
        '''</summary>
        Friend Shared ReadOnly Property mensaje_chat_finalizado() As String
            Get
                Return ResourceManager.GetString("mensaje_chat_finalizado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nueva contraseña.
        '''</summary>
        Friend Shared ReadOnly Property nueva_contrasenna() As String
            Get
                Return ResourceManager.GetString("nueva_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Posibles Diagnósticos.
        '''</summary>
        Friend Shared ReadOnly Property posibles_diagnosticos() As String
            Get
                Return ResourceManager.GetString("posibles_diagnosticos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Restablecer Contraseña.
        '''</summary>
        Friend Shared ReadOnly Property restablecer_contrasenna() As String
            Get
                Return ResourceManager.GetString("restablecer_contrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntomas Ingresados.
        '''</summary>
        Friend Shared ReadOnly Property sintomas_ingresados() As String
            Get
                Return ResourceManager.GetString("sintomas_ingresados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntomas Registrados.
        '''</summary>
        Friend Shared ReadOnly Property sintomas_registrados() As String
            Get
                Return ResourceManager.GetString("sintomas_registrados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat Finalizado.
        '''</summary>
        Friend Shared ReadOnly Property titulo_chat_finalizado() As String
            Get
                Return ResourceManager.GetString("titulo_chat_finalizado", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
